" Color
set background=dark
colorscheme zenburn

" Indenting
set noexpandtab                  " use tabs, not spaces
set tabstop=8                    " tabstops of 8
set shiftwidth=8                 " indents of 8
set textwidth=78                 " screen in 80 columns wide, wrap at 78
set autoindent smartindent       " turn on auto/smart indenting
set smarttab                     " make <tab> and <backspace> smarter
set backspace=eol,start,indent   " allow backspacing over indent, eol, & start
filetype plugin indent on        " indent code differently based on file type

" Highlighting
syntax on
autocmd Syntax * syn match ExtraWhitespace /\s\+$\| \+\ze\t/
autocmd Syntax * syn match Error80         /\%>80v.\+/ 

" Spell-check
setlocal spell spelllang=en_us

augroup filetypedetect
au BufNewFile,BufRead *.R        setf R
au BufNewFile,BufRead *.mk       setf markdown
au BufNewFile,BufRead *.markdown setf markdown
augroup END

" C formatting (from Linux kernel style guide)
set formatoptions=tcqlron
set cinoptions=:0,l1,t0,g0

