# Enable programmable completion features.
if which -s brew; then
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
    fi
elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi

# Set the PS1 prompt (with colors).
# Based on http://www-128.ibm.com/developerworks/linux/library/l-tip-prompt/
# And http://networking.ringofsaturn.com/Unix/Bash-prompts.php .
if type __git_ps1 >/dev/null 2>&1; then
	PS1='\[\e[36;1m\]\h:\[\e[32;1m\]\w\[\e[31;1m\]$(__git_ps1 " (%s)")\[\e[36;1m\]\$ \[\e[0m\]'
else
	PS1="\[\e[36;1m\]\h:\[\e[32;1m\]\w$ \[\e[0m\]"
fi

# Set the default editor to MacVim.
EDITOR=vim
if [ -x /usr/local/bin/mvim ]; then
    VISUAL='mvim -f'
fi



# Avoid succesive duplicates in the bash command history.
export HISTCONTROL=ignoredups

# Append commands to the bash command history file (~/.bash_history)
# instead of overwriting it.
shopt -s histappend

# Append commands to the history every time a prompt is shown,
# instead of after closing the session.
PROMPT_COMMAND='history -a'

# Link GSL with Accelerate instead of GSL CBLAS
if [ -d /System/Library/Frameworks/Accelerate.framework ]; then
	export GSL_CBLAS_LIB="-framework Accelerate"
fi

# Add bash aliases.
if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi

# RVM
if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    source "$HOME/.rvm/scripts/rvm"
fi

# Cabal
PATH="$HOME/.cabal/bin:/Library/Cabal/bin:$PATH" # cabal-installed binaries

### Heroku Toolbelt
if [ -d /usr/local/heroku/bin ]; then
    PATH="/usr/local/heroku/bin:$PATH"
fi
